
export const themes = {
    physical: {
        title: "Physical Fundamentals",
        icon: "🌱",
        description: "Understanding the core physical aspects of breastfeeding - how your body works, proper positioning, and milk production.",
        color: "#e91e63"
    },
    patterns: {
        title: "Feeding Patterns & Schedules",
        icon: "⏰",
        description: "Learning your baby's hunger cues, feeding frequency, and understanding normal feeding patterns throughout development.",
        color: "#9c27b0"
    },
    maternal: {
        title: "Maternal Health & Wellbeing",
        icon: "💖",
        description: "Taking care of yourself - nutrition, breast health, emotional wellbeing, and managing common complications.",
        color: "#ff9800"
    },
    skills: {
        title: "Practical Skills",
        icon: "🛠️",
        description: "Essential techniques for pumping, storage, night feeding, and maintaining your breastfeeding routine.",
        color: "#2196f3"
    },
    transitions: {
        title: "Transitions & Milestones",
        icon: "🌈",
        description: "Navigating major changes - introducing solids, returning to work, and eventual weaning when you're ready.",
        color: "#4caf50"
    },
    social: {
        title: "Social & Support Systems",
        icon: "🤝",
        description: "Building your support network, breastfeeding in public, and accessing resources for special circumstances.",
        color: "#00bcd4"
    }
};

export const topics = [
    { id: 1, title: "Latch & Positioning", icon: "👶", theme: "physical", preview: "Master proper attachment", attrs: { definition: "How baby attaches to breast", importance: "Prevents damage, ensures milk transfer", timing: "Learn before birth", techniques: "Cradle, cross-cradle, football, side-lying positions", signs: "Wide mouth (140-160°), flanged lips, rhythmic sucking, audible swallowing", problems: "Shallow latch affects 60-80% first-time mothers, nipple pain 79-96%", solutions: "Adjust baby position, bring baby to breast not breast to baby", help: "Pain beyond 1 week, cracked/bleeding nipples", duration: "1-2 weeks to master (14 days average first-time, 5-7 experienced)", resources: "Hospital lactation consultants, La Leche League, IBCLC", partner: "Position pillows, bring baby to mother, provide feedback", cultural: "Different positions preferred in different cultures" } },

    { id: 2, title: "Milk Supply", icon: "💧", theme: "physical", preview: "Supply-demand mechanisms", attrs: { definition: "Breast milk creation and maintenance through hormonal regulation", importance: "Ensures baby receives adequate nutrition for growth", timing: "Begins pregnancy, dramatically increases after delivery", techniques: "8-12 feeds/24 hours, responsive feeding, complete breast emptying", signs: "6+ wet diapers daily, weight gain 150-200g/week, satisfied baby", problems: "Perceived low supply 35-50% (usually adequate), true insufficiency only 2-5%", solutions: "Nurse frequently, ensure effective latch, adequate hydration 3-4L daily", help: "Baby losing weight, fewer than 6 wet diapers, not back to birth weight by 2 weeks", duration: "Supply-demand regulation 6-12 weeks to fully establish", resources: "Lactation consultants for weighted feeds, pediatrician, breast pump", partner: "Bring baby for night feedings, manage household tasks", cultural: "Traditional foods believed to increase supply (oats, fenugreek)" } },

    { id: 3, title: "Colostrum", icon: "🥇", theme: "physical", preview: "First milk immunological power", attrs: { definition: "First milk produced - thick, yellow, extremely high in antibodies", importance: "Provides passive immunity, prevents infection, aids meconium passage", timing: "Present mid-pregnancy, produced first 2-5 days postpartum", techniques: "Hand expression, frequent nursing in small concentrated amounts", signs: "Small amounts appropriate to stomach: Day 1: 5-7mL, Day 2: 10-15mL, Day 3: 15-30mL", problems: "Worry about 'not enough' milk, some cultures incorrectly discard colostrum", solutions: "Understand newborn stomach is marble-sized (5-7mL), colostrum highly concentrated", help: "Baby excessively sleepy not waking to feed, no feeding within first hours", duration: "Pure colostrum days 1-2, transitional milk days 3-5, mature milk by days 10-14", resources: "Prenatal breastfeeding classes explaining colostrum importance", partner: "Reassure mother about small amounts being normal, track feeding frequency", cultural: "18-45% of certain cultures discard colostrum - actively discourage this" } },

    { id: 4, title: "Feeding Frequency", icon: "⏰", theme: "patterns", preview: "Timing and hunger cues", attrs: { definition: "How often and how long baby nurses varying by age", importance: "Establishes adequate supply, ensures proper nutrition and hydration", timing: "Newborn: every 1.5-3 hours, Weeks 2-6: 8-10 feeds, Months 2-4: 6-8 feeds", techniques: "Watch hunger cues not clock, allow cluster feeding (normal)", signs: "8-12 feeds per 24 hours early weeks, baby satisfied after feeding", problems: "Cluster feeding misconceptions, external pressure to schedule feeds", solutions: "Feed on demand, expect growth spurt clusters at predictable times", help: "Newborn sleeping >4 hours without eating until back to birth weight", duration: "10-45 minutes per session initially, becoming more efficient over time", resources: "Baby tracking apps (Huckleberry, Baby Tracker), feeding logs", partner: "Track feeds if helpful, manage visitors during cluster periods", cultural: "Western cultures push schedules; traditional cultures practice demand feeding" } },

    { id: 5, title: "Growth Spurts", icon: "📈", theme: "patterns", preview: "Temporary increased feeding", attrs: { definition: "Periods of dramatically increased feeding frequency lasting 24-72 hours", importance: "Baby increasing mother's supply for upcoming needs - NOT supply problem", timing: "Common at 2-3 weeks, 6 weeks, 3 months, 6 months, 9 months, 12 months", techniques: "Allow unlimited increased feeding, don't supplement unnecessarily", signs: "Increased feeding 24-48 hours then return to normal, weight gain follows", problems: "Mother worries about low supply (35-60% during spurts)", solutions: "Understand temporary (48 hours average), rest, accept help with household", help: "Spurt extends beyond 3 days, baby seems ill with fever/lethargy", duration: "Usually 24-72 hours per spurt, corresponding weight gain 150-200g following week", resources: "Growth chart tracking, pediatrician reassurance for expectation setting", partner: "Manage household tasks, bring meals to nursing mother, minimize visitors", cultural: "Different interpretations of constant feeding (insufficient milk vs. normal)" } },

    { id: 6, title: "Breast Health", icon: "🩹", theme: "maternal", preview: "Prevention and treatment", attrs: { definition: "Maintaining breast and nipple condition to prevent infection and damage", importance: "Prevents mastitis (10-33% of mothers), thrush, abscess formation", timing: "Begin preventive care immediately postpartum, address issues promptly", techniques: "Air dry after feeds, express milk on nipples (healing), proper latch", signs: "Minimal tenderness after first week, intact skin, breasts soft between feeds", problems: "Cracked nipples 34-96%, thrush 5-20%, mastitis 10-33%, plugged ducts 15-25%", solutions: "Lanolin cream, correct latch immediately, warm compresses, antibiotics for mastitis", help: "Cracked/bleeding nipples, fever >101°F, red streaks on breast", duration: "Initial sensitivity normal 3-7 days, trauma heals 3-7 days with intervention", resources: "Medical-grade lanolin, hydrogel pads, lactation consultant assessment", partner: "Help apply treatments, watch for infection signs (fever, redness)", cultural: "Traditional remedies vary (ghee, herbal preparations) - verify safety" } },

    { id: 7, title: "Nutrition", icon: "🥗", theme: "maternal", preview: "Supporting production", attrs: { definition: "Mother's dietary and fluid needs to support milk production and health", importance: "Supports 750-1000mL daily production, maternal energy and recovery", timing: "Increase intake immediately postpartum, maintain throughout breastfeeding", techniques: "+450-500 extra calories daily, 3-4L fluids, balanced nutrient-dense meals", signs: "Adequate milk supply, mother feels energized, pale yellow urine", problems: "Dehydration (headache, dizziness), poor nutrition, excessive weight loss >1kg/week", solutions: "Water bottle at each nursing station, nutrient-dense snacks readily available", help: "Dizziness, extreme fatigue, dark concentrated urine, supply decrease", duration: "Entire breastfeeding period - needs remain elevated as long as nursing", resources: "Nutritionist consultation, postpartum meal delivery services", partner: "Prepare meals, keep water accessible at nursing stations, provide snacks", cultural: "Postpartum dietary traditions (hot/cold food balance, specific soups)" } },

    { id: 8, title: "Mental Health", icon: "🧠", theme: "maternal", preview: "Psychological wellbeing", attrs: { definition: "Mother's psychological and emotional wellbeing during breastfeeding", importance: "Affects bonding, milk supply (stress inhibits oxytocin), family health", timing: "Monitor from birth through weaning, highest PPD/PPA risk first 6 months", techniques: "Self-care practices, adequate rest, social support, therapy when needed", signs: "Feeling bonded with baby, manageable stress, enjoying motherhood moments", problems: "Postpartum depression 10-20%, anxiety 10-15%, D-MER, breastfeeding aversion", solutions: "Professional mental health care, breastfeeding-compatible medications available", help: "Persistent sadness >2 weeks, intrusive thoughts, inability to bond, self-harm thoughts", duration: "Risk highest first 6 months postpartum, can occur throughout first year", resources: "Perinatal mental health therapist, psychiatrist, Postpartum Support International", partner: "Watch for warning signs (crying, withdrawal), encourage treatment, provide support", cultural: "Significant mental health stigma in many cultures, variable access to care" } },

    { id: 9, title: "Medications", icon: "💊", theme: "maternal", preview: "Drug safety", attrs: { definition: "Understanding safety of medications and substances during breastfeeding", importance: "Protects baby while allowing mother necessary treatment - most ARE compatible", timing: "Review all medications before and during breastfeeding, check each new prescription", techniques: "Consult LactMed database (free NIH resource), ask prescribers about compatibility", signs: "Mother receives necessary medical treatment safely without stopping breastfeeding", problems: "Unnecessary medication avoidance (mother not treating conditions), unsafe use", solutions: "Find breastfeeding-compatible alternatives for most medications, time doses after nursing", help: "Any new prescription, OTC medication questions, infant behavior changes after maternal medication", duration: "Throughout entire breastfeeding period - check each and every medication", resources: "LactMed database (free, updated), InfantRisk Center hotline, pharmacist", partner: "Help research medications using LactMed, remind about optimal timing of doses", cultural: "Different comfort levels with pharmaceutical vs. traditional/herbal remedies" } },

    { id: 10, title: "Pumping", icon: "🍼", theme: "skills", preview: "Expressing and storing", attrs: { definition: "Expressing breast milk using manual or electric pumps and storing safely", importance: "Allows work return, builds freezer stash, maintains supply during separation", timing: "Establish breastfeeding first (3-4 weeks) before introducing pump except medical necessity", techniques: "Double electric pump most efficient, hands-on pumping increases output 48%", signs: "Accumulated freezer stash, maintained milk supply, efficient sessions 60-120mL", problems: "Low pump output (pump less efficient than baby - normal), storage confusion", solutions: "Pump at regular times, look at baby photo (oxytocin), correct flange size (nipple + 2-4mm)", help: "Pumping painful (check flange fit), significant supply decrease, unable to pump enough", duration: "Storage: room temp 4 hours, fridge 4 days, freezer 6-12 months, Sessions: 15-20 minutes", resources: "Breast pump through insurance (mandated coverage), storage bags, labeling system", partner: "Wash pump parts daily, organize stored milk (oldest first), give bottles for rest", cultural: "Workplace pumping rights vary dramatically (US: PUMP Act requires accommodations)" } },

    { id: 11, title: "Night Feeding", icon: "🌙", theme: "skills", preview: "Safe nighttime nursing", attrs: { definition: "Managing breastfeeding during nighttime hours maintaining safety and rest", importance: "Maintains milk supply (prolactin peaks 2-6 AM), supports infant sleep patterns", timing: "Expect 2-4 night feedings initially, gradually decreasing over 6-12 months", techniques: "Side-lying nursing, room-sharing, dream feeding (10-11 PM), minimize lights", signs: "Both mother and baby return to sleep easily, safe sleep practices maintained", problems: "Severe exhaustion affecting daily function, unsafe sleep practices (recliner)", solutions: "Partner shift system (4-6 hour consolidated sleep), nap when baby naps, safe bedsharing if chosen", help: "Severe sleep deprivation affecting function, unsafe behaviors, hallucinations from exhaustion", duration: "Night feeds decrease: 0-4 weeks (3-5 feeds), 1-2 months (2-4), 7-12 months (0-2)", resources: "Safe sleep guidelines (AAP), Safe Sleep Seven for bedsharing, sleep consultants", partner: "Change diapers, bring baby to mother, resettle baby after feeding, handle morning shift", cultural: "Bedsharing practices vary - Western medicine discourages but 60-75% mothers do it" } },

    { id: 12, title: "Bottles & Pacifiers", icon: "🍼", theme: "skills", preview: "Safe alternative introduction", attrs: { definition: "Offering bottles and pacifiers as alternatives or supplements to direct breastfeeding", importance: "Can support breastfeeding success (flexibility) or interfere (nipple confusion)", timing: "Wait 3-4 weeks for bottle introduction to establish breastfeeding, evaluate pacifier necessity", techniques: "Paced bottle feeding (horizontal position, frequent pauses), slow-flow nipples", signs: "Baby accepts bottle but still breastfeeds well, no reduction in nursing frequency or supply", problems: "Nipple confusion (baby preferring bottle's faster flow), bottle/pacifier refusal", solutions: "Maintain breast priority (always nurse first), have partner/others give bottles", help: "Baby refusing breast after bottles introduced, supply dropping significantly", duration: "Gradual introduction over several attempts (1-2 weeks), occasional refusal normal initially", resources: "Lactation consultant for bottle introduction guidance, various bottle brands to try", partner: "Give bottles to allow mother rest or enable work, maintain feeding schedule, monitor preferences", cultural: "Pacifier use culturally variable - common in US/Europe, less common in some Asian cultures" } },

    { id: 13, title: "Work Return", icon: "💼", theme: "transitions", preview: "Maintaining while employed", attrs: { definition: "Continuing breastfeeding while returning to employment through pumping and planning", importance: "Allows continuation of breastfeeding benefits despite work separation", timing: "Plan 2-4 weeks before return date, build freezer stash, practice bottle feeding", techniques: "Pump every 3-4 hours during work, pump at times baby would normally nurse", signs: "Maintained milk supply matching baby's needs, baby accepts bottles from caregiver", problems: "Supply decrease from reduced frequency, lack of workplace support, time constraints", solutions: "Know your rights (PUMP Act in US), pump during breaks, maintain night nursing", help: "Workplace discrimination/lack of accommodations, significant supply drop, mastitis from missed sessions", duration: "Varies by work schedule and breastfeeding goals, can continue through toddlerhood", resources: "Workplace lactation rooms (required), PUMP Act information, portable high-quality pumps", partner: "Handle morning routine efficiently, manage stored milk organization, bottle feed during work", cultural: "Maternity leave varies dramatically: US (0-12 weeks unpaid), Europe (6-12+ months paid)" } },

    { id: 14, title: "Introducing Solids", icon: "🥄", theme: "transitions", preview: "Complementary feeding", attrs: { definition: "Beginning solid foods around 6 months while continuing breastfeeding as primary nutrition", importance: "Meets increasing nutritional needs (especially iron/zinc), important developmental milestone", timing: "Around 6 months when baby shows readiness: sits independently, interest in food, lost tongue-thrust", techniques: "Baby-led weaning or purees (both work), continue nursing BEFORE offering solids", signs: "Baby interested in food, continued robust breastfeeding, meeting nutritional needs", problems: "Too early introduction (<6 months), replacing breastfeeding with solids, food allergies", solutions: "Nurse before solids to maintain supply, gradual introduction one food at a time", help: "Allergic reactions (rash, vomiting, bloody stools), feeding difficulties, significant supply drop", duration: "Gradual increase over months - breast milk primary nutrition through 12 months despite solids", resources: "Pediatrician feeding guidance, feeding therapist if difficulties, allergy testing if family history", partner: "Prepare age-appropriate foods, participate in family meals, clean up messes enthusiastically", cultural: "First foods vary by culture (rice cereal vs. mashed foods vs. family foods from start)" } },

    { id: 15, title: "Weaning", icon: "🌅", theme: "transitions", preview: "Transition from breastfeeding", attrs: { definition: "Gradual or sudden ending of breastfeeding relationship - timing and method vary widely", importance: "Should be respectful of both mother's and baby's needs, minimize discomfort, preserve bond", timing: "Varies widely - WHO recommends through age 2+, many wean earlier, some nurse into childhood", techniques: "Drop one feeding at a time gradually ('don't offer, don't refuse'), baby-led vs. mother-led", signs: "Gradual transition without severe engorgement or distress for either party, maintained connection", problems: "External pressure to wean early, abrupt weaning causing engorgement/mastitis, maternal guilt", solutions: "Follow your own timeline not others' expectations, gradual reduction over weeks/months", help: "Severe engorgement during weaning, emotional difficulty coping, depression symptoms emerging", duration: "Can take weeks to months depending on approach - gradual weaning typically easiest on both", resources: "Lactation consultant for weaning guidance, support groups, mental health support if needed", partner: "Provide comfort to baby during transition, support mother's decision without judgment", cultural: "Weaning age expectations vary dramatically: US average 6-9 months, globally 2-4 years common" } },

    { id: 16, title: "Weight Gain", icon: "⚖️", theme: "patterns", preview: "Tracking intake", attrs: { definition: "Monitoring baby's growth patterns and elimination as primary intake indicators", importance: "Primary objective measure of adequate milk intake - more reliable than perception", timing: "Daily monitoring early on (first 2 weeks), then weekly weight checks, monthly pediatric visits", techniques: "Track wet/dirty diapers (simple chart), regular weight checks (same scale, same time)", signs: "6+ wet diapers daily, back to birth weight by 2 weeks, gain 150-200g/week first 3 months", problems: "Slow weight gain, excessive weight loss (>10% from birth), dehydration signs", solutions: "Increase feeding frequency, improve latch efficiency, possible supplementation if medically indicated", help: "Weight loss >10% from birth, fewer than 6 wet diapers daily, dark concentrated urine, lethargy", duration: "Close monitoring first 2 weeks critical, then regular pediatric visits (2 weeks, 1, 2, 4, 6 months)", resources: "Pediatrician visits for weight checks, home baby scale rental, lactation consultant weighted feeds", partner: "Track diapers on shared chart, attend weight check appointments, observe baby's alertness", cultural: "Different growth expectations and chart usage (WHO vs. CDC charts have different curves)" } },

    { id: 17, title: "Complications", icon: "⚠️", theme: "maternal", preview: "Medical issue treatment", attrs: { definition: "Medical issues arising during breastfeeding requiring professional treatment and intervention", importance: "Early recognition prevents serious complications like abscess (3-11% of untreated mastitis)", timing: "Can occur any time during breastfeeding journey, most common in early weeks", techniques: "Prevention through proper latch, frequent complete emptying, good hygiene, stress management", signs: "Quick identification and appropriate treatment, resolution without breastfeeding interruption", problems: "Mastitis 10-33%, thrush 5-20%, plugged ducts 15-25%, tongue tie, nipple trauma, low supply", solutions: "Warm compresses/massage, continue nursing, antibiotics for mastitis, antifungals for thrush, frenotomy", help: "Fever >101°F, red streaks on breast, white patches in baby's mouth, persistent pain, supply concerns", duration: "Treatment varies: plugged ducts (24-48 hours), mastitis (10-14 day antibiotics), thrush (14-21 days)", resources: "Pediatrician, lactation consultant (IBCLC), oral surgeon for tongue ties, infectious disease specialist", partner: "Monitor symptoms closely, encourage prompt medical care, assist with treatments, attend appointments", cultural: "Different comfort levels with medical intervention, traditional remedies may or may not help" } },

    { id: 18, title: "Support Systems", icon: "🤝", theme: "social", preview: "Building help network", attrs: { definition: "Network of people, professionals, and services available to support breastfeeding success", importance: "Dramatically increases breastfeeding success rates and duration, provides problem-solving resources", timing: "Build network during pregnancy and early postpartum period, ongoing throughout journey", techniques: "Join support groups, hire/consult IBCLC, educate partner, connect with experienced mothers", signs: "Quick access to help when problems arise, feeling supported and informed, confident decisions", problems: "Isolation, conflicting advice from multiple sources, lack of knowledgeable support, geographic barriers", solutions: "Find evidence-based sources, La Leche League meetings (free), online communities, telehealth options", help: "Feeling alone and overwhelmed, receiving harmful advice, unable to find local resources", duration: "Ongoing throughout breastfeeding journey - needs change but support remains important", resources: "IBCLC (gold standard), pediatrician, WIC program, breastfeeding support groups, peer counselors", partner: "Research resources, attend lactation appointments, filter unhelpful visitors/advice, provide encouragement", cultural: "Community support structures vary (extended family involvement vs. nuclear family isolation)" } },

    { id: 19, title: "Public Feeding", icon: "👥", theme: "social", preview: "Nursing confidently", attrs: { definition: "Feeding baby outside home environment in public spaces and social situations", importance: "Allows mother and baby freedom to participate in normal life, essential for mental health", timing: "Practice at home with mirror first, venture out when comfortable (usually weeks 2-4)", techniques: "Nursing covers optional, two-shirt method (lift one, pull down other), know your legal rights", signs: "Confident feeding anywhere baby is hungry, comfortable with chosen method, aware of rights", problems: "Self-consciousness, lack of comfortable accommodations, inappropriate comments from strangers", solutions: "Practice builds confidence, know state laws protect nursing in public, have prepared responses", help: "Harassment or discrimination, severe anxiety preventing necessary outings with baby", duration: "Throughout entire breastfeeding period - becomes more natural with practice and confidence", resources: "Nursing room finder apps (Moms Pump Here), state law information, supportive online communities", partner: "Provide moral support, run interference with inappropriate comments, help find comfortable spots", cultural: "Public breastfeeding acceptance varies dramatically - legally protected in US, taboo in some cultures" } },

    { id: 20, title: "Special Circumstances", icon: "⭐", theme: "social", preview: "Complex situations", attrs: { definition: "Breastfeeding with complications: multiples, premature babies, medical conditions, anatomical issues", importance: "Requires specialized knowledge and support but breast milk benefits are even more critical", timing: "Address from birth or diagnosis, immediate specialized lactation support essential for success", techniques: "Tandem nursing (twins), triple feeding protocol, exclusive pumping, specialized positioning, supplementation", signs: "Babies receiving breast milk despite challenges, sustainable long-term plan established, adequate support", problems: "Supply issues with multiples, NICU separation barriers, coordination difficulties, tongue/lip ties", solutions: "Hospital-grade pump essential, specialized lactation consultant with relevant experience, specific protocols", help: "Immediately upon diagnosis or complication - don't wait, early intervention absolutely critical for outcomes", duration: "Depends on specific circumstance - some temporary challenges, some ongoing throughout breastfeeding", resources: "NICU lactation consultants, specialists in multiples/prematurity, condition-specific support groups", partner: "Extra hands absolutely essential for success, attend all medical appointments, emotional support critical", cultural: "Access to specialized resources varies dramatically by location, some cultures more accepting of challenges" } }
];

export const bodyChanges = {
    0: {
        title: "Birth & Initial Days",
        changes: [
            { title: "Colostrum Production", desc: "Thick, yellow first milk rich in antibodies. Produced in small amounts (2-20mL per feed)." },
            { title: "Breast Fullness", desc: "Breasts may feel soft. This is normal - colostrum is concentrated and baby's stomach is tiny (5-7mL)." },
            { title: "Hormonal Shift", desc: "Prolactin levels spike after placenta delivery, triggering milk production system." }
        ]
    },
    1: {
        title: "Week 1 - Milk Coming In",
        changes: [
            { title: "Engorgement", desc: "Days 2-5: Breasts become full, warm, heavy as transitional milk arrives. Size increases 1-2 cup sizes temporarily." },
            { title: "Increased Volume", desc: "Production jumps from 30-60mL daily to 300-750mL by day 5. Dramatic increase." },
            { title: "Nipple Sensitivity", desc: "Initial tenderness normal (3-5/10 pain scale). Should decrease significantly by end of week." }
        ]
    },
    2: {
        title: "Week 2 - Establishing Pattern",
        changes: [
            { title: "Supply Regulation", desc: "Body learning baby's needs. Producing 500-750mL daily. Breasts may feel less full between feeds (normal)." },
            { title: "Letdown Sensation", desc: "May feel tingling, pins-and-needles during milk release. Can happen 2-5 times per feed." },
            { title: "Leaking", desc: "Common in early weeks. One breast may leak while feeding from other. Breast pads helpful." }
        ]
    },
    6: {
        title: "Week 6 - Supply Stabilizing",
        changes: [
            { title: "Autocrine Control", desc: "Transitioning from hormone-driven to demand-driven supply. Body responding directly to baby's needs." },
            { title: "Growth Spurt", desc: "Common this week. Baby may feed constantly 24-48 hours to increase supply. This is normal!" },
            { title: "Breast Size", desc: "Breasts may feel softer, less full. This is good - means supply is well-regulated, not decreasing." }
        ]
    },
    12: {
        title: "Week 12 - Mature Supply",
        changes: [
            { title: "Full Regulation", desc: "Supply-demand system fully established. Producing 750-1000mL daily based on baby's needs." },
            { title: "Efficient Feeding", desc: "Baby getting faster at feeding. Sessions may shorten to 10-20 minutes." },
            { title: "Comfortable Routine", desc: "Most mothers report breastfeeding feels natural, automatic, pain-free by now." }
        ]
    },
    26: {
        title: "Week 26 (6 Months) - Introducing Solids",
        changes: [
            { title: "Continued Production", desc: "Still producing 750-1000mL daily. Breast milk remains primary nutrition source." },
            { title: "Feeding Pattern Shift", desc: "May notice baby nursing before meals, using breast for comfort as well as nutrition." },
            { title: "Body Adaptation", desc: "Breasts adapt to produce nutritionally complete milk with higher fat content in shorter feeds." }
        ]
    },
    52: {
        title: "Week 52 (1 Year) - Extended Breastfeeding",
        changes: [
            { title: "Ongoing Benefits", desc: "Milk composition adapts to toddler's needs. Producing 400-600mL daily with solid foods." },
            { title: "Immune Support", desc: "Antibodies remain high. Extended breastfeeding provides ongoing immune protection." },
            { title: "Comfort & Connection", desc: "Breastfeeding provides emotional security and bonding beyond nutrition." }
        ]
    }
};
