
// This file is generated to break the circular dependency between Routes.tsx and page components.
export const ROUTES = {
    LANDING: "/",
    HOME: "/home",
    DASHBOARD: "/dashboard",
    LOGOUT: "/logout",
    JOURNEYS: "/journeys",
    PREGNANCY: "/journeys/pregnancy",
    FERTILITY: "/journeys/fertility",
    PREVENTIVE_HEALTH: "/journeys/preventive-health",
    MENSTRUAL_HEALTH: "/journeys/menstrual-health",
    CHRONIC_CONDITIONS: "/journeys/chronic-conditions",
    MENTAL_WELLNESS: "/journeys/mental-wellness",
    POSTPARTUM: "/journeys/postpartum",
    ADOLESCENT_HEALTH: "/journeys/adolescent-health",
    MENOPAUSE: "/journeys/menopause",
    PRODUCTS: "/products",
    APPOINTMENTS: "/teleconsultation",  // Point appointments to teleconsultation page
    COMMUNITY: "/community",
    SYMPTOM_CHECKER: "/symptom-checker",
    SAFETY: "/safety",
    SUPPORT: "/support",
    // STORIES: "/stories",
    ABOUT: "/about",
    PERINATAL: "/journeys/perinatal",
    GOVERNMENT_SCHEMES: "/government-schemes",
    RESEARCH: "/research",
    COSMETIC_SURGERY: "/cosmetic-surgery",
    PERINATAL_FAMILY: "/perinatal-family-guide",
    TELECONSULTATION: "/teleconsultation",
    FIND_DOCTORS: "/find-doctors",
    SCREENING: "/screening",
    VACCINATION: "/vaccination",
    SERVICES: "/services",
    GYNAECOLOGY_OB: "/services/gynaecology-ob",
    INSURANCE_GUIDE: "/insurance-guide",
    BREASTFEEDING: "/journeys/breastfeeding",
    LOSS_SUPPORT: "/journeys/loss-support",
    OTC_GUIDE: "/otc-guide",
    NUTRITION_GUIDE: "/nutrition-guide",
    AESTHETIC_SIMULATOR: "/cosmetic-surgery/simulator",
    PERINATAL_WELLNESS: "/journeys/perinatal-wellness",
    AUTOIMMUNE_HEALTH: "/journeys/autoimmune-health",
    BONE_HEALTH: "/journeys/bone-health",
    CANCER_VISUALIZATION: "/visualizations/cancer",
    HORMONAL_HEALTH: "/journeys/hormonal-health",
    GESTATIONAL_DIABETES: "/journeys/gestational-diabetes",
    PREECLAMPSIA_EDUCATION: "/journeys/preeclampsia-education",
    FERTILITY_JOURNEY: "/journeys/fertility-journey",
    CONCEPTION_GUIDE: "/journeys/conception-guide",
    MILK_SUPPLY_GUIDE: "/journeys/milk-supply-guide",
} as const;
